#!/usr/bin/bash
tomocupy recon --file-name $1 --remove-stripe-method fw --reconstruction-type full --rotation-axis-auto auto --find-center-end-row 1500
# tomocupy recon_steps --file-name $1 --reconstruction-type full --rotation-axis $2 --remove-stripe-method fw  --retrieve-phase-method paganin --retrieve-phase-alpha 0.0001 --energy 30 --propagation-distance 100 --pixel-size $3 --fbp-filter shepp --nsino-per-chunk 16 --nproj-per-chunk 16
# tomolog run --presentation-url https://docs.google.com/presentation/d/1mD6yNr_gyPXelGVN1oB_z7zY5eiDS-NBkbm8mtZMVlI/edit?usp=sharing --file-name $1 --beamline 2-bm --zoom [1,2,4]
# tomolog run --presentation-url https://docs.google.com/presentation/d/1WxNLek-DrLMGrOzqvfRkU9V4jkfavyat4HDrLEqst3Q/edit#slide=id.a9f91db5-5db0-4415-b371-72ca74b22a17 --file-name $1 --beamline 2-bm --idx 1100 --idy 1400 --idz 450 --magnification -1 --min -0.0001 --max 0.0001
tomolog run --presentation-url https://docs.google.com/presentation/d/1YuxMttfW8w2sfwbaw65R3_LgPIsaHblz4Lrsjzn6ufQ/edit?usp=sharing --file-name $1 --beamline 2-bm --zoom [1,2,4]
